---
- hosts: all


  vars:
    gather_facts: true
    ansible_user: ec2-user
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true
    installs: 1
    outpath: "/home/ec2-user/openscap/out-{{ ansible_date_time.date }}"
    outfile: "{{ outpath }}/openscap-{{ ansible_hostname }}.html"

  tasks:
   - name: Install OpenSCAP
     yum:
       pkg: openscap-scanner
       state: installed
     when: installs == 1

   - name: Install SCAP Def
     yum:
       pkg: scap-security-guide
       state: installed
     when: installs == 1

   - name: Create Dir for output
     file: path={{ outpath }} state=directory mode=0700 owner=ec2-user

   - name: Run OSCAP
     shell: oscap xccdf eval --report {{ outfile}} --profile xccdf_org.ssgproject.content_profile_pci-dss /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
     ignore_errors: true

   - name: Fetch output from node
     fetch: src={{ outfile}} dest={{ outfile}} flat=yes


