- name: Fix audispd to active
  lineinfile:
    path: /etc/audisp/plugins.d/syslog.conf
    regexp: "^active"
    line: "active = yes"
    state: present

- name: Restart auditd
  systemd:
    state: restarted
    daemon_reload: yes
    name: auditd